// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/home.html"
    | "/icon/icon128.png"
    | "/icon/icon16.png"
    | "/icon/icon22.png"
    | "/icon/icon32.png"
    | "/icon/icon48.png"
    | "/sidepanel.html"
    | "/test-target.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
